In [1]:
#Importing the requored libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, model_selection, linear_model

In [2]:
X, y = datasets.load_linnerud(return_X_y=True)
print(X.shape)
print(X[0])

(20, 3)
[  5. 162.  60.]


In [3]:
X.shape

(20, 3)

In [4]:
X

array([[  5., 162.,  60.],
       [  2., 110.,  60.],
       [ 12., 101., 101.],
       [ 12., 105.,  37.],
       [ 13., 155.,  58.],
       [  4., 101.,  42.],
       [  8., 101.,  38.],
       [  6., 125.,  40.],
       [ 15., 200.,  40.],
       [ 17., 251., 250.],
       [ 17., 120.,  38.],
       [ 13., 210., 115.],
       [ 14., 215., 105.],
       [  1.,  50.,  50.],
       [  6.,  70.,  31.],
       [ 12., 210., 120.],
       [  4.,  60.,  25.],
       [ 11., 230.,  80.],
       [ 15., 225.,  73.],
       [  2., 110.,  43.]])

In [5]:
y

array([[191.,  36.,  50.],
       [189.,  37.,  52.],
       [193.,  38.,  58.],
       [162.,  35.,  62.],
       [189.,  35.,  46.],
       [182.,  36.,  56.],
       [211.,  38.,  56.],
       [167.,  34.,  60.],
       [176.,  31.,  74.],
       [154.,  33.,  56.],
       [169.,  34.,  50.],
       [166.,  33.,  52.],
       [154.,  34.,  64.],
       [247.,  46.,  50.],
       [193.,  36.,  46.],
       [202.,  37.,  62.],
       [176.,  37.,  54.],
       [157.,  32.,  52.],
       [156.,  33.,  54.],
       [138.,  33.,  68.]])

In [6]:
#splitting both the data (X) and the target (y) into test and training sets

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.3)

In [7]:
# Training the model
model = linear_model.LinearRegression()
model.fit(X_train, y_train)


LinearRegression()

In [9]:
# Making a prediction using test data
y_pred = model.predict(X_test)

In [ ]:
# The plot
plt.scatter(X_test, y_test,  color='black')
plt.plot(X_test, y_pred, color='red', linewidth=3)
plt.ylabel('Waist')
plt.xlabel('Situp')
plt.title('Relationshipe between Waistand Situp')
plt.show()